# Generated by Django 2.2.1 on 2020-02-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematikuj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocetni_priklady',
            options={'verbose_name': 'Příklad', 'verbose_name_plural': 'Příklady'},
        ),
    ]
