# Generated by Django 2.2.1 on 2020-02-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matematikuj', '0002_auto_20200208_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['tema', 'podtema', 'kapitola'], 'verbose_name': 'Téma', 'verbose_name_plural': 'Témata'},
        ),
    ]
